INSERT INTO news (
    slug,
    category,
    title,
    excerpt,
    body,
    author,
    reading_time,
    cover_image,
    caption,
    formats,
    published_at,
    is_published
)
VALUES
(
    'masa-depan-atlet-disabilitas-setelah-podium',
    'Liputan Khusus',
    'Di Balik Podium: Menyiapkan Masa Depan Atlet Disabilitas',
    'Prestasi di arena belum selalu diikuti kepastian pendidikan, pekerjaan, dan perlindungan setelah masa kompetisi berakhir.',
    '<p>Medali menjadi simbol kerja keras, tetapi kehidupan atlet tidak berhenti di podium. Banyak atlet disabilitas masih harus menyusun sendiri rencana pendidikan, pekerjaan, dan jaminan ekonomi setelah masa kompetisi selesai.</p><h2>Dukungan yang berkelanjutan</h2><p>Program transisi karier perlu dimulai sejak atlet masih aktif. Pelatihan keterampilan, akses beasiswa, dan kemitraan dengan dunia kerja dapat membantu atlet membangun pilihan hidup yang lebih luas.</p>',
    'Tim Paravoice',
    12,
    'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80',
    'Atlet bersiap sebelum memasuki arena pertandingan.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-13T09:00:00+07:00',
    TRUE
),
(
    'latihan-tanpa-fasilitas-yang-setara',
    'Para Report',
    'Latihan Setiap Hari, Fasilitas Belum Setara',
    'Sejumlah atlet tetap menjaga ritme latihan di tengah keterbatasan akses terhadap arena dan perlengkapan adaptif.',
    '<p>Jadwal latihan yang padat tidak selalu didukung fasilitas yang memadai. Sebagian atlet harus berbagi ruang dengan pengguna umum atau menempuh perjalanan panjang untuk menemukan tempat latihan yang aksesibel.</p><h2>Standar aksesibilitas</h2><p>Fasilitas olahraga publik dapat menjadi bagian dari solusi apabila akses masuk, ruang ganti, toilet, dan peralatannya dirancang untuk kebutuhan yang beragam.</p>',
    'Nadia Prameswari',
    7,
    'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80',
    'Sesi latihan atlet di fasilitas olahraga publik.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-12T14:00:00+07:00',
    TRUE
),
(
    'panduan-liputan-disabilitas-yang-bermartabat',
    'Para Edu',
    'Panduan Liputan Disabilitas yang Bermartabat',
    'Pilihan kata, sudut pandang, dan proses wawancara menentukan apakah sebuah liputan memperkuat atau justru mengikis martabat narasumber.',
    '<p>Liputan disabilitas perlu berangkat dari pengalaman dan agensi narasumber. Jurnalis sebaiknya menghindari bahasa yang mengasihani, dramatisasi berlebihan, serta asumsi tentang kemampuan seseorang.</p><h2>Tanyakan preferensi narasumber</h2><p>Gunakan istilah yang dipilih narasumber, jelaskan kebutuhan akses selama wawancara, dan berikan ruang bagi konteks sosial yang memengaruhi pengalaman mereka.</p>',
    'Salsa Anindita',
    9,
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    'Catatan reporter saat menyiapkan proses wawancara.',
    ARRAY['TEKS'],
    '2026-06-11T10:30:00+07:00',
    TRUE
),
(
    'maulida-aulia-melampaui-batas',
    'Para Atlet',
    'Maulida Aulia: Melampaui Batas dengan Lompatan Harapan',
    'Disiplin, dukungan keluarga, dan keberanian mencoba kembali menjadi bagian penting dari perjalanan seorang atlet menuju level nasional.',
    '<p>Setiap lompatan menyimpan proses panjang yang tidak selalu terlihat penonton. Maulida membangun konsistensi melalui latihan teknik, penguatan fisik, dan evaluasi rutin bersama pelatih.</p><h2>Lebih dari hasil pertandingan</h2><p>Baginya, olahraga juga membuka ruang pertemanan, kemandirian, dan kesempatan untuk menunjukkan bahwa prestasi tumbuh dari lingkungan yang mendukung.</p>',
    'Raka Mahendra',
    8,
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    'Atlet para-atletik menjalani sesi latihan lintasan.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-10T16:00:00+07:00',
    TRUE
),
(
    'membaca-anggaran-olahraga-disabilitas',
    'Para Data',
    'Membaca Anggaran Olahraga Disabilitas di Daerah',
    'Data anggaran menunjukkan dukungan yang belum merata antara pembinaan rutin, kompetisi, dan penyediaan fasilitas aksesibel.',
    '<p>Besarnya anggaran bukan satu-satunya ukuran keberpihakan. Cara anggaran dibagi menentukan apakah pembinaan dapat berlangsung sepanjang tahun atau hanya menguat menjelang kompetisi.</p><h2>Transparansi dan dampak</h2><p>Publik perlu dapat melihat alokasi untuk pelatih, peralatan adaptif, transportasi, klasifikasi atlet, dan peningkatan fasilitas agar dampak program dapat dievaluasi.</p>',
    'Desk Data Paravoice',
    10,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'Visualisasi data untuk membaca distribusi anggaran.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-09T11:00:00+07:00',
    TRUE
),
(
    'film-dan-representasi-disabilitas',
    'Para Pop',
    'Ketika Film Memberi Ruang pada Karakter Disabilitas',
    'Representasi yang kuat hadir ketika karakter disabilitas memiliki tujuan, konflik, humor, dan kehidupan yang utuh.',
    '<p>Karakter disabilitas masih kerap ditempatkan sebagai simbol inspirasi atau objek belas kasihan. Padahal, cerita yang lebih menarik lahir ketika mereka ditulis sebagai manusia dengan pengalaman yang kompleks.</p><h2>Melibatkan kreator disabilitas</h2><p>Keterlibatan penulis, aktor, dan konsultan disabilitas membantu produksi menghindari stereotip sekaligus menemukan detail yang lebih jujur.</p>',
    'Dimas Ardiansyah',
    6,
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    'Layar bioskop sebagai ruang tumbuhnya representasi.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-08T19:00:00+07:00',
    TRUE
),
(
    'transportasi-publik-menuju-arena-olahraga',
    'Para Report',
    'Perjalanan Panjang Menuju Arena yang Aksesibel',
    'Bagi sebagian atlet, tantangan latihan dimulai bahkan sebelum mereka tiba di arena olahraga.',
    '<p>Trotoar yang terputus, kendaraan yang belum aksesibel, dan jarak antarmoda membuat perjalanan menuju tempat latihan memerlukan waktu serta biaya tambahan.</p><h2>Akses adalah bagian dari pembinaan</h2><p>Dukungan transportasi dan pemilihan lokasi latihan yang terhubung angkutan umum perlu dihitung sebagai bagian dari ekosistem prestasi, bukan kebutuhan tambahan.</p>',
    'Ayu Lestari',
    7,
    'https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1200&q=80',
    'Mobilitas perkotaan menuju pusat kegiatan olahraga.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-07T08:00:00+07:00',
    TRUE
),
(
    'mengenal-klasifikasi-dalam-para-olahraga',
    'Para Edu',
    'Mengenal Klasifikasi dalam Para Olahraga',
    'Sistem klasifikasi membantu memastikan kompetisi berlangsung adil berdasarkan dampak hambatan terhadap performa olahraga.',
    '<p>Klasifikasi bukan penilaian atas nilai atau kemampuan seseorang. Proses ini mengelompokkan atlet berdasarkan sejauh mana hambatan memengaruhi aktivitas spesifik dalam cabang olahraga.</p><h2>Proses yang terus dievaluasi</h2><p>Atlet dapat menjalani pemeriksaan medis, observasi teknis, dan evaluasi saat bertanding. Klasifikasi juga dapat ditinjau kembali seiring perubahan kondisi atau aturan cabang olahraga.</p>',
    'Tim Edukasi Paravoice',
    8,
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
    'Kompetisi olahraga membutuhkan sistem pertandingan yang adil.',
    ARRAY['TEKS'],
    '2026-06-06T13:30:00+07:00',
    TRUE
),
(
    'teknologi-bantu-dan-performa-atlet',
    'Para Data',
    'Teknologi Bantu yang Mengubah Cara Atlet Berlatih',
    'Peralatan adaptif, sensor gerak, dan analisis video memberi pelatih data baru untuk menyusun latihan yang lebih presisi.',
    '<p>Inovasi teknologi membantu atlet memahami pola gerak, beban latihan, dan risiko cedera. Namun, manfaatnya sangat bergantung pada akses, biaya perawatan, dan kemampuan tim membaca data.</p><h2>Teknologi yang tepat guna</h2><p>Investasi terbaik tidak selalu berarti alat paling mahal. Perangkat perlu dipilih berdasarkan kebutuhan atlet, kemudahan perawatan, serta dukungan teknis yang tersedia.</p>',
    'Desk Data Paravoice',
    9,
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    'Teknologi digunakan untuk menganalisis dan meningkatkan performa.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-05T15:00:00+07:00',
    TRUE
),
(
    'komunitas-lari-inklusif-di-kota',
    'Para Pop',
    'Komunitas Lari Inklusif Membuka Ruang Pertemanan Baru',
    'Kegiatan olahraga berbasis komunitas menunjukkan bahwa aksesibilitas dapat tumbuh dari kebiasaan sederhana dan komunikasi terbuka.',
    '<p>Komunitas lari inklusif mempertemukan peserta dengan pengalaman yang beragam. Pendamping, pengelola rute, dan peserta belajar membangun ritme kegiatan yang aman serta nyaman bersama-sama.</p><h2>Dimulai dari mendengarkan</h2><p>Rute yang rata, informasi yang jelas, titik istirahat, dan kesediaan menyesuaikan metode pendampingan membuat kegiatan dapat diikuti lebih banyak orang.</p>',
    'Farhan Nugraha',
    5,
    'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80',
    'Komunitas olahraga berlatih bersama di ruang terbuka.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-04T07:00:00+07:00',
    TRUE
)
ON CONFLICT (slug) DO UPDATE SET
    category = EXCLUDED.category,
    title = EXCLUDED.title,
    excerpt = EXCLUDED.excerpt,
    body = EXCLUDED.body,
    author = EXCLUDED.author,
    reading_time = EXCLUDED.reading_time,
    cover_image = EXCLUDED.cover_image,
    caption = EXCLUDED.caption,
    formats = EXCLUDED.formats,
    published_at = EXCLUDED.published_at,
    is_published = EXCLUDED.is_published,
    updated_at = NOW();
