INSERT INTO news (
    slug,
    category,
    title,
    excerpt,
    body,
    author,
    reading_time,
    cover_image,
    caption,
    formats,
    published_at,
    is_published
)
VALUES
(
    'masa-depan-atlet-disabilitas-setelah-podium',
    'Liputan Khusus',
    'Di Balik Podium: Menyiapkan Masa Depan Atlet Disabilitas',
    'Prestasi di arena belum selalu diikuti kepastian pendidikan, pekerjaan, dan perlindungan setelah masa kompetisi berakhir.',
    '<p>Medali menjadi simbol kerja keras, tetapi kehidupan atlet tidak berhenti di podium. Banyak atlet disabilitas masih harus menyusun sendiri rencana pendidikan, pekerjaan, dan jaminan ekonomi setelah masa kompetisi selesai.</p><h2>Dukungan yang berkelanjutan</h2><p>Program transisi karier perlu dimulai sejak atlet masih aktif. Pelatihan keterampilan, akses beasiswa, dan kemitraan dengan dunia kerja dapat membantu atlet membangun pilihan hidup yang lebih luas.</p>',
    'Tim Paravoice',
    12,
    'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80',
    'Atlet bersiap sebelum memasuki arena pertandingan.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-13T09:00:00+07:00',
    TRUE
),
(
    'maulida-aulia-melampaui-batas',
    'Para Atlet',
    'Maulida Aulia: Melampaui Batas dengan Lompatan Harapan',
    'Disiplin, dukungan keluarga, dan keberanian mencoba kembali menjadi bagian penting dari perjalanan menuju level nasional.',
    '<p>Disiplin, dukungan keluarga, dan keberanian mencoba kembali menjadi bagian penting dari perjalanan menuju level nasional. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Paravoice',
    5,
    'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80',
    'Atlet para-atletik menjalani sesi latihan lintasan.',
    ARRAY['TEKS'],
    '2026-06-12T20:00:00+07:00',
    TRUE
),
(
    'bangkit-dari-cedera-perenang-muda',
    'Para Atlet',
    'Bangkit dari Cedera, Perenang Muda Kembali ke Lintasan',
    'Setelah masa pemulihan yang panjang, ia menemukan cara baru untuk membangun kekuatan dan kepercayaan diri.',
    '<p>Setelah masa pemulihan yang panjang, ia menemukan cara baru untuk membangun kekuatan dan kepercayaan diri. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Nadia Prameswari',
    6,
    'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80',
    'Perenang menjalani sesi pemulihan di kolam latihan.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-12T14:00:00+07:00',
    TRUE
),
(
    'rekor-daerah-angkat-berat',
    'Para Atlet',
    'Kisah Atlet Angkat Berat yang Memecahkan Rekor Daerah',
    'Latihan terukur dan pendampingan pelatih membawa rekor baru sekaligus harapan bagi atlet muda lainnya.',
    '<p>Latihan terukur dan pendampingan pelatih membawa rekor baru sekaligus harapan bagi atlet muda lainnya. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Salsa Anindita',
    7,
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    'Atlet para-powerlifting saat sesi latihan beban.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-12T08:00:00+07:00',
    TRUE
),
(
    'pelari-tunanetra-dan-pendamping',
    'Para Atlet',
    'Pelari Tunanetra dan Pendamping yang Menjadi Mata Kedua',
    'Sinkronisasi langkah dan komunikasi yang erat menjadi kunci di setiap meter lintasan.',
    '<p>Sinkronisasi langkah dan komunikasi yang erat menjadi kunci di setiap meter lintasan. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Raka Mahendra',
    8,
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    'Pelari dan pendamping berlatih bersama di lintasan.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-12T02:00:00+07:00',
    TRUE
),
(
    'atlet-catur-membaca-papan',
    'Para Atlet',
    'Atlet Catur yang Membaca Papan dengan Sentuhan',
    'Konsentrasi dan ingatan posisi yang tajam membuktikan bahwa strategi tidak mengenal batas.',
    '<p>Konsentrasi dan ingatan posisi yang tajam membuktikan bahwa strategi tidak mengenal batas. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Desk Data Paravoice',
    9,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'Papan catur adaptif yang dirancang untuk diraba.',
    ARRAY['TEKS'],
    '2026-06-11T20:00:00+07:00',
    TRUE
),
(
    'dari-lapangan-kampung-ke-nasional',
    'Para Atlet',
    'Dari Lapangan Kampung ke Panggung Nasional',
    'Perjalanan dimulai dari fasilitas seadanya hingga akhirnya membela daerah di ajang nasional.',
    '<p>Perjalanan dimulai dari fasilitas seadanya hingga akhirnya membela daerah di ajang nasional. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Dimas Ardiansyah',
    10,
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    'Atlet berlatih di lapangan terbuka dekat rumah.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-11T14:00:00+07:00',
    TRUE
),
(
    'petenis-kursi-roda-mengubah-tekanan',
    'Para Atlet',
    'Petenis Kursi Roda yang Mengubah Tekanan Jadi Tenaga',
    'Manuver cepat dan ketenangan di poin kritis menjadi senjata utamanya di lapangan.',
    '<p>Manuver cepat dan ketenangan di poin kritis menjadi senjata utamanya di lapangan. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Ayu Lestari',
    11,
    'https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1200&q=80',
    'Petenis kursi roda saat pertandingan latihan.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-11T08:00:00+07:00',
    TRUE
),
(
    'atlet-panahan-menemukan-fokus',
    'Para Atlet',
    'Atlet Panahan yang Menemukan Fokus di Tengah Keterbatasan',
    'Rutinitas pernapasan dan pengulangan teknik membentuk konsistensi tembakan demi tembakan.',
    '<p>Rutinitas pernapasan dan pengulangan teknik membentuk konsistensi tembakan demi tembakan. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Farhan Nugraha',
    12,
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
    'Atlet panahan membidik sasaran saat latihan.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-11T02:00:00+07:00',
    TRUE
),
(
    'juara-bulu-tangkis-para',
    'Para Atlet',
    'Juara Bulu Tangkis Para yang Berlatih Tanpa Lelah',
    'Kombinasi kecepatan kaki dan penempatan kok yang cermat membawanya naik ke peringkat atas.',
    '<p>Kombinasi kecepatan kaki dan penempatan kok yang cermat membawanya naik ke peringkat atas. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Edukasi Paravoice',
    5,
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    'Atlet para-badminton dalam sesi latihan.',
    ARRAY['TEKS'],
    '2026-06-10T20:00:00+07:00',
    TRUE
),
(
    'perjalanan-atlet-boccia',
    'Para Atlet',
    'Perjalanan Atlet Boccia Menuju Klasifikasi Internasional',
    'Ketelitian melempar dan strategi membaca lawan menjadi inti dari olahraga presisi ini.',
    '<p>Ketelitian melempar dan strategi membaca lawan menjadi inti dari olahraga presisi ini. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Bagas Wicaksono',
    6,
    'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80',
    'Bola boccia ditata sebelum giliran bermain.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-10T14:00:00+07:00',
    TRUE
),
(
    'film-dan-representasi-disabilitas',
    'Para Pop',
    'Ketika Film Memberi Ruang pada Karakter Disabilitas',
    'Representasi yang kuat hadir ketika karakter memiliki tujuan, konflik, humor, dan kehidupan yang utuh.',
    '<p>Representasi yang kuat hadir ketika karakter memiliki tujuan, konflik, humor, dan kehidupan yang utuh. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Citra Maharani',
    7,
    'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80',
    'Layar bioskop sebagai ruang tumbuhnya representasi.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-10T08:00:00+07:00',
    TRUE
),
(
    'komunitas-lari-inklusif-di-kota',
    'Para Pop',
    'Komunitas Lari Inklusif Membuka Ruang Pertemanan Baru',
    'Kegiatan berbasis komunitas menunjukkan aksesibilitas dapat tumbuh dari kebiasaan sederhana.',
    '<p>Kegiatan berbasis komunitas menunjukkan aksesibilitas dapat tumbuh dari kebiasaan sederhana. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Yoga Pratama',
    8,
    'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80',
    'Komunitas olahraga berlatih bersama di ruang terbuka.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-10T02:00:00+07:00',
    TRUE
),
(
    'musisi-tunarungu-merasakan-irama',
    'Para Pop',
    'Musisi Tunarungu dan Cara Baru Merasakan Irama',
    'Getaran, visual, dan kolaborasi membuka jalan untuk berkarya di panggung musik.',
    '<p>Getaran, visual, dan kolaborasi membuka jalan untuk berkarya di panggung musik. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Paravoice',
    9,
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    'Panggung musik dengan tata cahaya yang ekspresif.',
    ARRAY['TEKS'],
    '2026-06-09T20:00:00+07:00',
    TRUE
),
(
    'serial-televisi-pahlawan-disabilitas',
    'Para Pop',
    'Serial Televisi yang Menampilkan Pahlawan Disabilitas',
    'Penonton menyambut cerita yang menempatkan tokoh disabilitas sebagai pusat narasi.',
    '<p>Penonton menyambut cerita yang menempatkan tokoh disabilitas sebagai pusat narasi. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Nadia Prameswari',
    10,
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    'Studio produksi serial televisi.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-09T14:00:00+07:00',
    TRUE
),
(
    'festival-seni-untuk-semua',
    'Para Pop',
    'Festival Seni yang Dirancang untuk Semua Pengunjung',
    'Jalur akses, juru bahasa isyarat, dan deskripsi audio membuat seni dapat dinikmati lebih luas.',
    '<p>Jalur akses, juru bahasa isyarat, dan deskripsi audio membuat seni dapat dinikmati lebih luas. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Salsa Anindita',
    11,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'Pengunjung menikmati karya di ruang pameran.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-09T08:00:00+07:00',
    TRUE
),
(
    'kreator-disabilitas-media-sosial',
    'Para Pop',
    'Konten Kreator Disabilitas yang Mengubah Narasi di Media Sosial',
    'Cerita sehari-hari yang jujur perlahan menggeser stereotip yang sudah lama melekat.',
    '<p>Cerita sehari-hari yang jujur perlahan menggeser stereotip yang sudah lama melekat. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Raka Mahendra',
    12,
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    'Kreator merekam konten di ruang kerja sederhana.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-09T02:00:00+07:00',
    TRUE
),
(
    'buku-anak-keberagaman-tubuh',
    'Para Pop',
    'Buku Anak yang Menormalkan Keberagaman Tubuh',
    'Ilustrasi dan kisah yang hangat mengenalkan inklusi sejak usia dini.',
    '<p>Ilustrasi dan kisah yang hangat mengenalkan inklusi sejak usia dini. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Desk Data Paravoice',
    5,
    'https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1200&q=80',
    'Buku cerita anak dengan ilustrasi penuh warna.',
    ARRAY['TEKS'],
    '2026-06-08T20:00:00+07:00',
    TRUE
),
(
    'game-video-fitur-aksesibilitas',
    'Para Pop',
    'Game Video yang Mengutamakan Fitur Aksesibilitas',
    'Opsi kontrol, teks, dan mode warna membuat permainan dapat dinikmati lebih banyak pemain.',
    '<p>Opsi kontrol, teks, dan mode warna membuat permainan dapat dinikmati lebih banyak pemain. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Dimas Ardiansyah',
    6,
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
    'Layar permainan dengan menu pengaturan aksesibilitas.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-08T14:00:00+07:00',
    TRUE
),
(
    'podcast-disabilitas-bongkar-stereotip',
    'Para Pop',
    'Podcast Disabilitas yang Membongkar Stereotip',
    'Percakapan terbuka menghadirkan sudut pandang yang jarang muncul di media arus utama.',
    '<p>Percakapan terbuka menghadirkan sudut pandang yang jarang muncul di media arus utama. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Ayu Lestari',
    7,
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    'Mikrofon di studio rekaman podcast.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-08T08:00:00+07:00',
    TRUE
),
(
    'pameran-foto-mobilitas-tanpa-batas',
    'Para Pop',
    'Pameran Foto yang Merayakan Mobilitas Tanpa Batas',
    'Bingkai demi bingkai menampilkan gerak, semangat, dan keseharian yang penuh warna.',
    '<p>Bingkai demi bingkai menampilkan gerak, semangat, dan keseharian yang penuh warna. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Farhan Nugraha',
    8,
    'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80',
    'Foto-foto dipajang di dinding galeri.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-08T02:00:00+07:00',
    TRUE
),
(
    'panduan-liputan-disabilitas-yang-bermartabat',
    'Para Edu',
    'Panduan Liputan Disabilitas yang Bermartabat',
    'Pilihan kata, sudut pandang, dan proses wawancara menentukan apakah liputan memperkuat martabat narasumber.',
    '<p>Pilihan kata, sudut pandang, dan proses wawancara menentukan apakah liputan memperkuat martabat narasumber. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Edukasi Paravoice',
    9,
    'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80',
    'Catatan reporter saat menyiapkan proses wawancara.',
    ARRAY['TEKS'],
    '2026-06-07T20:00:00+07:00',
    TRUE
),
(
    'mengenal-klasifikasi-dalam-para-olahraga',
    'Para Edu',
    'Mengenal Klasifikasi dalam Para Olahraga',
    'Sistem klasifikasi membantu memastikan kompetisi berlangsung adil berdasarkan dampak hambatan terhadap performa.',
    '<p>Sistem klasifikasi membantu memastikan kompetisi berlangsung adil berdasarkan dampak hambatan terhadap performa. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Bagas Wicaksono',
    10,
    'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80',
    'Kompetisi olahraga membutuhkan sistem pertandingan yang adil.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-07T14:00:00+07:00',
    TRUE
),
(
    'memahami-bahasa-ramah-disabilitas',
    'Para Edu',
    'Memahami Bahasa yang Ramah Disabilitas',
    'Istilah yang tepat menghormati pengalaman dan agensi setiap orang yang kita tulis.',
    '<p>Istilah yang tepat menghormati pengalaman dan agensi setiap orang yang kita tulis. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Citra Maharani',
    11,
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    'Buku catatan berisi panduan istilah.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-07T08:00:00+07:00',
    TRUE
),
(
    'dasar-aksesibilitas-fasilitas-olahraga',
    'Para Edu',
    'Dasar-Dasar Aksesibilitas di Fasilitas Olahraga',
    'Jalur landai, toilet, dan ruang ganti yang dirancang baik menentukan siapa saja yang bisa berlatih.',
    '<p>Jalur landai, toilet, dan ruang ganti yang dirancang baik menentukan siapa saja yang bisa berlatih. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Yoga Pratama',
    12,
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    'Jalur akses di sebuah fasilitas olahraga.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-07T02:00:00+07:00',
    TRUE
),
(
    'cara-mendampingi-atlet-tunanetra',
    'Para Edu',
    'Cara Mendampingi Atlet Tunanetra dengan Tepat',
    'Komunikasi yang jelas dan kesepakatan aba-aba menjaga keamanan sekaligus kepercayaan.',
    '<p>Komunikasi yang jelas dan kesepakatan aba-aba menjaga keamanan sekaligus kepercayaan. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Paravoice',
    5,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'Pendamping memberi arahan kepada atlet.',
    ARRAY['TEKS'],
    '2026-06-06T20:00:00+07:00',
    TRUE
),
(
    'mengenal-cabang-para-atletik',
    'Para Edu',
    'Mengenal Cabang-Cabang Para Atletik',
    'Dari lari hingga lempar, setiap nomor punya aturan dan klasifikasi tersendiri.',
    '<p>Dari lari hingga lempar, setiap nomor punya aturan dan klasifikasi tersendiri. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Nadia Prameswari',
    6,
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    'Lintasan atletik di stadion latihan.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-06T14:00:00+07:00',
    TRUE
),
(
    'etika-memotret-mewawancarai-atlet',
    'Para Edu',
    'Etika Memotret dan Mewawancarai Atlet Disabilitas',
    'Persetujuan, konteks, dan rasa hormat menjadi dasar dari setiap karya jurnalistik.',
    '<p>Persetujuan, konteks, dan rasa hormat menjadi dasar dari setiap karya jurnalistik. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Salsa Anindita',
    7,
    'https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1200&q=80',
    'Fotografer bersiap mengambil gambar atlet.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-06T08:00:00+07:00',
    TRUE
),
(
    'pertolongan-pertama-inklusif-di-arena',
    'Para Edu',
    'Pertolongan Pertama yang Inklusif di Arena',
    'Tim medis perlu memahami kebutuhan beragam agar penanganan cepat dan tepat.',
    '<p>Tim medis perlu memahami kebutuhan beragam agar penanganan cepat dan tepat. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Raka Mahendra',
    8,
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
    'Petugas medis bersiaga di pinggir lapangan.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-06T02:00:00+07:00',
    TRUE
),
(
    'membangun-sekolah-olahraga-inklusif',
    'Para Edu',
    'Membangun Sekolah Olahraga yang Inklusif',
    'Kurikulum, pelatih, dan fasilitas yang adaptif membuka pintu bagi lebih banyak bakat.',
    '<p>Kurikulum, pelatih, dan fasilitas yang adaptif membuka pintu bagi lebih banyak bakat. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Desk Data Paravoice',
    9,
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    'Ruang latihan di sebuah sekolah olahraga.',
    ARRAY['TEKS'],
    '2026-06-05T20:00:00+07:00',
    TRUE
),
(
    'panduan-orang-tua-anak-atlet',
    'Para Edu',
    'Panduan Orang Tua Mendukung Anak Atlet Disabilitas',
    'Dukungan emosional dan perencanaan yang realistis membantu anak berkembang tanpa tekanan berlebih.',
    '<p>Dukungan emosional dan perencanaan yang realistis membantu anak berkembang tanpa tekanan berlebih. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Dimas Ardiansyah',
    10,
    'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80',
    'Orang tua mendampingi anak berlatih.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-05T14:00:00+07:00',
    TRUE
),
(
    'latihan-tanpa-fasilitas-yang-setara',
    'Para Report',
    'Latihan Setiap Hari, Fasilitas Belum Setara',
    'Sejumlah atlet tetap menjaga ritme latihan di tengah keterbatasan akses arena dan perlengkapan adaptif.',
    '<p>Sejumlah atlet tetap menjaga ritme latihan di tengah keterbatasan akses arena dan perlengkapan adaptif. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Ayu Lestari',
    11,
    'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80',
    'Sesi latihan atlet di fasilitas olahraga publik.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-05T08:00:00+07:00',
    TRUE
),
(
    'transportasi-publik-menuju-arena-olahraga',
    'Para Report',
    'Perjalanan Panjang Menuju Arena yang Aksesibel',
    'Bagi sebagian atlet, tantangan latihan dimulai bahkan sebelum mereka tiba di arena olahraga.',
    '<p>Bagi sebagian atlet, tantangan latihan dimulai bahkan sebelum mereka tiba di arena olahraga. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Farhan Nugraha',
    12,
    'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80',
    'Mobilitas perkotaan menuju pusat kegiatan olahraga.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-05T02:00:00+07:00',
    TRUE
),
(
    'menanti-bonus-yang-tak-kunjung-cair',
    'Para Report',
    'Menanti Bonus yang Tak Kunjung Cair',
    'Janji penghargaan setelah kompetisi kerap tertunda dan menambah beban ekonomi atlet.',
    '<p>Janji penghargaan setelah kompetisi kerap tertunda dan menambah beban ekonomi atlet. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Edukasi Paravoice',
    5,
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    'Atlet menunggu kepastian setelah kompetisi.',
    ARRAY['TEKS'],
    '2026-06-04T20:00:00+07:00',
    TRUE
),
(
    'pelatih-merangkap-banyak-peran',
    'Para Report',
    'Ketika Pelatih Harus Merangkap Banyak Peran',
    'Keterbatasan tenaga membuat satu pelatih menangani latihan, logistik, hingga administrasi.',
    '<p>Keterbatasan tenaga membuat satu pelatih menangani latihan, logistik, hingga administrasi. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Bagas Wicaksono',
    6,
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    'Pelatih menyusun program latihan harian.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-04T14:00:00+07:00',
    TRUE
),
(
    'arena-megah-akses-masih-terhambat',
    'Para Report',
    'Arena Megah, Akses Masuk Masih Terhambat',
    'Bangunan baru belum tentu ramah bagi pengguna kursi roda dan kebutuhan akses lainnya.',
    '<p>Bangunan baru belum tentu ramah bagi pengguna kursi roda dan kebutuhan akses lainnya. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Citra Maharani',
    7,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'Pintu masuk arena olahraga yang baru dibangun.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-04T08:00:00+07:00',
    TRUE
),
(
    'pembinaan-usia-dini-kekurangan-pelatih',
    'Para Report',
    'Pembinaan Usia Dini yang Kekurangan Pelatih',
    'Minimnya pelatih bersertifikat menghambat penjaringan bakat sejak bangku sekolah.',
    '<p>Minimnya pelatih bersertifikat menghambat penjaringan bakat sejak bangku sekolah. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Yoga Pratama',
    8,
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    'Anak-anak berlatih di lapangan sekolah.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-04T02:00:00+07:00',
    TRUE
),
(
    'atlet-membiayai-latihan-sendiri',
    'Para Report',
    'Cerita Atlet yang Membiayai Latihan Sendiri',
    'Tanpa dukungan tetap, sebagian atlet menanggung biaya peralatan dan perjalanan dari kantong pribadi.',
    '<p>Tanpa dukungan tetap, sebagian atlet menanggung biaya peralatan dan perjalanan dari kantong pribadi. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Paravoice',
    9,
    'https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1200&q=80',
    'Peralatan latihan milik pribadi atlet.',
    ARRAY['TEKS'],
    '2026-06-03T20:00:00+07:00',
    TRUE
),
(
    'kesenjangan-fasilitas-kota-dan-daerah',
    'Para Report',
    'Kesenjangan Fasilitas antara Kota dan Daerah',
    'Akses terhadap arena dan peralatan adaptif masih timpang antarwilayah.',
    '<p>Akses terhadap arena dan peralatan adaptif masih timpang antarwilayah. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Nadia Prameswari',
    10,
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
    'Fasilitas olahraga sederhana di daerah.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-03T14:00:00+07:00',
    TRUE
),
(
    'jaminan-kesehatan-atlet-abu-abu',
    'Para Report',
    'Jaminan Kesehatan Atlet yang Masih Abu-Abu',
    'Perlindungan saat cedera menjadi pertanyaan yang belum sepenuhnya terjawab.',
    '<p>Perlindungan saat cedera menjadi pertanyaan yang belum sepenuhnya terjawab. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Salsa Anindita',
    11,
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    'Ruang fisioterapi untuk pemulihan atlet.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-03T08:00:00+07:00',
    TRUE
),
(
    'setelah-pensiun-atlet-cari-jalan',
    'Para Report',
    'Setelah Pensiun, Atlet Mencari Jalan Baru',
    'Transisi karier yang minim pendampingan membuat masa setelah kompetisi terasa berat.',
    '<p>Transisi karier yang minim pendampingan membuat masa setelah kompetisi terasa berat. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Raka Mahendra',
    12,
    'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80',
    'Atlet merenungkan langkah setelah pensiun.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-03T02:00:00+07:00',
    TRUE
),
(
    'membaca-anggaran-olahraga-disabilitas',
    'Para Data',
    'Membaca Anggaran Olahraga Disabilitas di Daerah',
    'Data anggaran menunjukkan dukungan yang belum merata antara pembinaan, kompetisi, dan fasilitas.',
    '<p>Data anggaran menunjukkan dukungan yang belum merata antara pembinaan, kompetisi, dan fasilitas. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Desk Data Paravoice',
    5,
    'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80',
    'Visualisasi data untuk membaca distribusi anggaran.',
    ARRAY['TEKS'],
    '2026-06-02T20:00:00+07:00',
    TRUE
),
(
    'teknologi-bantu-dan-performa-atlet',
    'Para Data',
    'Teknologi Bantu yang Mengubah Cara Atlet Berlatih',
    'Peralatan adaptif, sensor gerak, dan analisis video memberi pelatih data baru yang lebih presisi.',
    '<p>Peralatan adaptif, sensor gerak, dan analisis video memberi pelatih data baru yang lebih presisi. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Dimas Ardiansyah',
    6,
    'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80',
    'Teknologi digunakan untuk menganalisis performa.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-02T14:00:00+07:00',
    TRUE
),
(
    'peta-sebaran-atlet-para',
    'Para Data',
    'Peta Sebaran Atlet Para di Seluruh Provinsi',
    'Pemetaan menunjukkan kantong-kantong bakat sekaligus wilayah yang masih perlu pembinaan.',
    '<p>Pemetaan menunjukkan kantong-kantong bakat sekaligus wilayah yang masih perlu pembinaan. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Ayu Lestari',
    7,
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    'Peta sebaran data ditampilkan di layar.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-02T08:00:00+07:00',
    TRUE
),
(
    'tren-medali-asean-para-games',
    'Para Data',
    'Tren Perolehan Medali Indonesia di ASEAN Para Games',
    'Catatan beberapa edisi memperlihatkan cabang yang konsisten menyumbang medali.',
    '<p>Catatan beberapa edisi memperlihatkan cabang yang konsisten menyumbang medali. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Farhan Nugraha',
    8,
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    'Grafik tren perolehan medali.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-02T02:00:00+07:00',
    TRUE
),
(
    'biaya-membina-satu-atlet',
    'Para Data',
    'Berapa Biaya Sebenarnya Membina Satu Atlet Para?',
    'Hitungan kasar mencakup pelatih, peralatan, transportasi, hingga klasifikasi.',
    '<p>Hitungan kasar mencakup pelatih, peralatan, transportasi, hingga klasifikasi. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Edukasi Paravoice',
    9,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'Rincian biaya dihitung di atas meja kerja.',
    ARRAY['TEKS'],
    '2026-06-01T20:00:00+07:00',
    TRUE
),
(
    'data-aksesibilitas-fasilitas-publik',
    'Para Data',
    'Data Aksesibilitas Fasilitas Olahraga Publik',
    'Survei sederhana mengungkap seberapa siap fasilitas menerima pengguna yang beragam.',
    '<p>Survei sederhana mengungkap seberapa siap fasilitas menerima pengguna yang beragam. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Bagas Wicaksono',
    10,
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    'Pengukuran aksesibilitas di lapangan.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-06-01T14:00:00+07:00',
    TRUE
),
(
    'statistik-cedera-para-olahraga',
    'Para Data',
    'Statistik Cedera dan Pencegahannya di Para Olahraga',
    'Pola cedera membantu tim menyusun program pemanasan dan pemulihan yang lebih aman.',
    '<p>Pola cedera membantu tim menyusun program pemanasan dan pemulihan yang lebih aman. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Langkah ke depan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Citra Maharani',
    11,
    'https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1200&q=80',
    'Catatan medis dan data cedera atlet.',
    ARRAY['TEKS', 'VIDEO'],
    '2026-06-01T08:00:00+07:00',
    TRUE
),
(
    'perbandingan-dukungan-sponsor',
    'Para Data',
    'Perbandingan Dukungan Sponsor Antarcabang',
    'Beberapa cabang lebih mudah menarik sponsor, sementara lainnya bergantung pada dana publik.',
    '<p>Beberapa cabang lebih mudah menarik sponsor, sementara lainnya bergantung pada dana publik. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Catatan dari lapangan</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Yoga Pratama',
    12,
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
    'Logo sponsor pada papan kompetisi.',
    ARRAY['TEKS', 'AUDIO', 'VIDEO'],
    '2026-06-01T02:00:00+07:00',
    TRUE
),
(
    'demografi-penonton-olahraga-disabilitas',
    'Para Data',
    'Demografi Penonton Olahraga Disabilitas',
    'Memahami siapa penontonnya membantu menyusun strategi siaran dan promosi.',
    '<p>Memahami siapa penontonnya membantu menyusun strategi siaran dan promosi. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Konteks yang perlu dipahami</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Tim Paravoice',
    5,
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    'Tribun penonton di arena pertandingan.',
    ARRAY['TEKS'],
    '2026-05-31T20:00:00+07:00',
    TRUE
),
(
    'memetakan-kebutuhan-pelatih-bersertifikat',
    'Para Data',
    'Memetakan Kebutuhan Pelatih Bersertifikat',
    'Data kebutuhan pelatih menjadi dasar perencanaan pelatihan dan sertifikasi.',
    '<p>Data kebutuhan pelatih menjadi dasar perencanaan pelatihan dan sertifikasi. Laporan ini menelusuri detail di baliknya melalui pengamatan langsung dan percakapan dengan pihak yang terlibat.</p><h2>Mengapa ini penting</h2><p>Setiap perubahan kecil dapat berdampak besar ketika dukungan diberikan secara konsisten. Paravoice mengangkat cerita, data, dan suara untuk mendorong ekosistem yang lebih inklusif bagi atlet disabilitas Indonesia.</p>',
    'Nadia Prameswari',
    6,
    'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80',
    'Sesi sertifikasi pelatih berlangsung.',
    ARRAY['TEKS', 'AUDIO'],
    '2026-05-31T14:00:00+07:00',
    TRUE
)
ON CONFLICT (slug) DO UPDATE SET
    category = EXCLUDED.category,
    title = EXCLUDED.title,
    excerpt = EXCLUDED.excerpt,
    body = EXCLUDED.body,
    author = EXCLUDED.author,
    reading_time = EXCLUDED.reading_time,
    cover_image = EXCLUDED.cover_image,
    caption = EXCLUDED.caption,
    formats = EXCLUDED.formats,
    published_at = EXCLUDED.published_at,
    is_published = EXCLUDED.is_published,
    updated_at = NOW();
